# application name
spring.application.name=taskflow

# database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
spring.datasource.username=postgres
spring.datasource.password=Rimrimrim123$$
spring.datasource.driver-class-name=org.postgresql.Driver

# this will show us the excuted sql code in the terminal
spring.jpa.show-sql=true

# if we create a new row and we don't have the table it will create the table
spring.jpa.hibernate.ddl-auto=update